name: satellite
services:
  frontend:
    image: caddy:latest
    restart: unless-stopped
    container_name: satellite-frontend
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/share/caddy
      - ./caddy-config:/etc/caddy
    depends_on:
      - backend
  backend:
    build: .
    container_name: satellite-backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    depends_on:
      - database
  database:
    image: mariadb:lts-ubi9
    container_name: satellite-database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
